--// File Generated By Fox-Warrior's Resources Generator Version 2.06 \\--

if (SERVER) then
  resource.AddSingleFile( "models/gagmouse/gagmousedroid.dx80.vtx" )
  resource.AddSingleFile( "models/gagmouse/gagmousedroid.dx90.vtx" )
  resource.AddSingleFile( "models/gagmouse/gagmousedroid.mdl" )
  resource.AddSingleFile( "models/gagmouse/gagmousedroid.phy" )
  resource.AddSingleFile( "models/gagmouse/gagmousedroid.sw.vtx" )
  resource.AddSingleFile( "models/gagmouse/gagmousedroid.vvd" )
  resource.AddSingleFile( "materials/models/gagmouse/FRC.vmt" )
  resource.AddSingleFile( "materials/models/gagmouse/FRC.vtf" )
  resource.AddSingleFile( "materials/models/gagmouse/Metal9.vmt" )
  resource.AddSingleFile( "materials/models/gagmouse/Metal9.vtf" )
end
