
list.Add("NPCUsableWeapons", {class = "rw_swnpc_random_empire", title = "[SW-RWK.Random Empire]"})
list.Add("NPCUsableWeapons", {class = "rw_swnpc_e11", title = "[SW-RWK] E-11"})
list.Add("NPCUsableWeapons", {class = "rw_swnpc_dlt19", title = "[SW-RWK] DLT-19"})
list.Add("NPCUsableWeapons", {class = "rw_swnpc_dlt19x", title = "[SW-RWK] DLT-19X"})
list.Add("NPCUsableWeapons", {class = "rw_swnpc_ec17", title = "[SW-RWK] EC-17"})
list.Add("NPCUsableWeapons", {class = "rw_swnpc_t21b", title = "[SW-RWK] T-21B"})

list.Add("NPCUsableWeapons", {class = "rw_swnpc_random_rebel", title = "[SW-RWK.Random Rebel]"})
list.Add("NPCUsableWeapons", {class = "rw_swnpc_a280", title = "[SW-RWK] A280"})
list.Add("NPCUsableWeapons", {class = "rw_swnpc_rt97c", title = "[SW-RWK] RT-97c"})
list.Add("NPCUsableWeapons", {class = "rw_swnpc_dlt20a", title = "[SW-RWK] DLT-20a"})
list.Add("NPCUsableWeapons", {class = "rw_swnpc_dh17", title = "[SW-RWK] DH-17"})
list.Add("NPCUsableWeapons", {class = "rw_swnpc_a280cfe", title = "[SW-RWK] A280-CFE"})

list.Add("NPCUsableWeapons", {class = "rw_swnpc_random_cis", title = "[SW-RWK.Random CIS]"})
list.Add("NPCUsableWeapons", {class = "rw_swnpc_e5", title = "[SW-RWK] E-5"})
list.Add("NPCUsableWeapons", {class = "rw_swnpc_e5c", title = "[SW-RWK] E-5c"})
list.Add("NPCUsableWeapons", {class = "rw_swnpc_e5s", title = "[SW-RWK] E-5s"})
list.Add("NPCUsableWeapons", {class = "rw_swnpc_se14", title = "[SW-RWK] SE-14"})
list.Add("NPCUsableWeapons", {class = "rw_swnpc_sg6", title = "[SW-RWK] SG-6"})
list.Add("NPCUsableWeapons", {class = "rw_swnpc_b2hand", title = "[SW-RWK] B2 Blaster-Hand"})

list.Add("NPCUsableWeapons", {class = "rw_swnpc_random_rep", title = "[SW-RWK.Random Republic]"})
list.Add("NPCUsableWeapons", {class = "rw_swnpc_dc15s", title = "[SW-RWK] DC-15S"})
list.Add("NPCUsableWeapons", {class = "rw_swnpc_dc15a", title = "[SW-RWK] DC-15A"})
list.Add("NPCUsableWeapons", {class = "rw_swnpc_dc17", title = "[SW-RWK] DC-17"})
list.Add("NPCUsableWeapons", {class = "rw_swnpc_dp23", title = "[SW-RWK] DP-23"})
list.Add("NPCUsableWeapons", {class = "rw_swnpc_valkenx38", title = "[SW-RWK] Valken x38"})