-- Misc --
util.AddNetworkString("QUEST_SYSTEM_ChatNotify_Player")
util.AddNetworkString("QUEST_SYSTEM_OpenDialogue")
-- Quest --
util.AddNetworkString("QUEST_SYSTEM_Quest_Add")
util.AddNetworkString("QUEST_SYSTEM_Quest_Remove")
util.AddNetworkString("QUEST_SYSTEM_Quest_Accept")
util.AddNetworkString("QUEST_SYSTEM_Quest_Abort")
util.AddNetworkString("QUEST_SYSTEM_Quest_Finish")
util.AddNetworkString("QUEST_SYSTEM_Quest_Client")
util.AddNetworkString("QUEST_SYSTEM_Quest_Progress")
util.AddNetworkString("sendpostionpilotquest")

net.Receive("QUEST_SYSTEM_Quest_Accept", function(numLength, sender)
	 local regquesttable = {"retrieval_crystal", "train_recruit", "pilot_flying", "pilot_drop", "interrogate", "inspection_1", "guardply_isb", "guard_isb", "guard_bridge", "guard_npcc", "navy", "guard_temple", "guardply_ihc", "guard_ihc", "medic_heal", "medic_1", "medic_revive", "grapple_hit", "jetpack", "cuff_3", "shield", "place_fortification", "janitor_1", "repairship", "throw_flashbang", "throw_thermaldet", "cloakmove", "sithforce", "duel"}
    local strQuest_ID = net.ReadString()
			if strQuest_ID == "pilot_flying" and sender:GetRegiment() == "Imperial Starfighter Corps" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "pilot_drop" and sender:GetRegiment() == "Imperial Starfighter Corps" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "interrogate" and sender:GetRegiment() == "Imperial Security Bureau" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "inspection_1" and sender:GetRegiment() == "Imperial Security Bureau" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "guardply_isb" and sender:GetRegiment() == "Death Trooper" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "guard_isb" and sender:GetRegiment() == "Death Trooper" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "guard_bridge" and sender:GetRegiment() == "Chimaera Squad" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
            elseif strQuest_ID == "guard_npcc" and sender:GetRegiment() == "Chimaera Squad" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "navy" and sender:GetRegiment() == "Imperial Navy" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "guard_temple" and sender:GetRegiment() == "Purge Trooper" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "guard_temple" and sender:GetRegiment() == "Imperial Guard" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "guard_temple" and sender:GetRegiment() == "Shadow Guard" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "guard_temple" and sender:GetRegiment() == "501st Vader's Fist" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "guardply_ihc" and sender:GetRegiment() == "996th Imperial Guard" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "guard_ihc" and sender:GetRegiment() == "107th Nova Company" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "medic_heal" and sender:GetRegiment() == "439th Medical Company" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
            elseif strQuest_ID == "medic_1" and sender:GetRegiment() == "439th Medical Company" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "medic_revive" and sender:GetRegiment() == "439th Medical Company" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "grapple_hit" and sender:GetRegiment() == "Range Trooper" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "grapple_hit" and sender:GetRegiment() == "501st Storm Commandos"then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "grapple_hit" and sender:GetJobTable().Name == "Cinder Sniper" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "grapple_hit" and (sender:HasWeapon("realistic_hook")) then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "jetpack" and sender:GetRegiment() == "17th Sky Divison" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "jetpack" and (sender:HasWeapon("weapon_jetpack")) then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "cuff_3" and (sender:HasWeapon("weapon_cuff_elastic")) then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "shield" and (sender:HasWeapon("weapon_policeshield")) then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "place_fortification" and sender:GetRegiment() == "Naval Engineer" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "janitor_1" and sender:GetRegiment() == "Naval Engineer" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "repairship" and sender:GetRegiment() == "Naval Engineer" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "throw_flashbang" and (sender:HasWeapon("zeus_flashbang")) then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "throw_thermaldet" and (sender:HasWeapon("zeus_thermaldet")) then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID) 
			elseif strQuest_ID == "cloakmove" and (sender:HasWeapon("weapon_camo")) then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "sithforce" and sender:GetRegiment() == "Sith" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "sithforce" and sender:GetRegiment() == "Imperial Inquisitor" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "sithforce" and sender:GetRegiment() == "Imperial Guard" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "sithforce" and sender:GetRegiment() == "Sith Marauder" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "duel" and sender:GetRegiment() == "Imperial Inquisitor" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "duel" and sender:GetRegiment() == "Imperial Guard" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "duel" and sender:GetRegiment() == "Sith Inquisitor" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "duel" and sender:GetRegiment() == "Shadow Guard" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif strQuest_ID == "duel" and sender:GetRegiment() == "Sith Marauder" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
            elseif strQuest_ID == "retrieval_crystal" and sender:GetRegiment() == "Sith" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
            elseif strQuest_ID == "retrieval_crystal" and sender:GetRegiment() == "Imperial Guard" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
            elseif strQuest_ID == "retrieval_crystal" and sender:GetRegiment() == "Imperial Inquisitor" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
            elseif strQuest_ID == "retrieval_crystal" and sender:GetRegiment() == "Shadow Guard" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
            elseif strQuest_ID == "retrieval_crystal" and sender:GetRegiment() == "Sith Marauder" then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)   
            elseif strQuest_ID == "train_recruit" and sender:GetRank() >= 4 then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID)
			elseif not table.HasValue(regquesttable, strQuest_ID) then sender:QUEST_SYSTEM_Quest_Accept(strQuest_ID) end
end)

net.Receive("QUEST_SYSTEM_Quest_Abort", function(numLength, sender)
    sender:QUEST_SYSTEM_Quest_Abort()
end)