NPC_WEAPONS_MIN_AIM_DELAY_NONE = 0.00
NPC_WEAPONS_MAX_AIM_DELAY_NONE = 0.00
NPC_WEAPONS_MIN_AIM_DELAY_LOW = 0.25
NPC_WEAPONS_MAX_AIM_DELAY_LOW = 0.25
NPC_WEAPONS_MIN_AIM_DELAY_MED = 0.25
NPC_WEAPONS_MAX_AIM_DELAY_MED = 0.50
NPC_WEAPONS_MIN_AIM_DELAY_HIGH = 0.50
NPC_WEAPONS_MAX_AIM_DELAY_HIGH = 1.00

NPC_WEAPONS_MIN_DROPOFF_DISTANCE_PISTOL = 512
NPC_WEAPONS_MAX_DROPOFF_DISTANCE_PISTOL = 2048
NPC_WEAPONS_MIN_DROPOFF_DISTANCE_SMG = 512
NPC_WEAPONS_MAX_DROPOFF_DISTANCE_SMG = 4048
NPC_WEAPONS_MIN_DROPOFF_DISTANCE_SHOTGUN = 256
NPC_WEAPONS_MAX_DROPOFF_DISTANCE_SHOTGUN = 2048
NPC_WEAPONS_MIN_DROPOFF_DISTANCE_RIFLE = 512
NPC_WEAPONS_MAX_DROPOFF_DISTANCE_RIFLE = 8096
NPC_WEAPONS_MIN_DROPOFF_DISTANCE_SNIPER = 512
NPC_WEAPONS_MAX_DROPOFF_DISTANCE_SNIPER = 10192

NPC_WEAPONS_SPREAD_MOVE_MULT_NONE = 0.6
NPC_WEAPONS_SPREAD_MOVE_MULT_LOW = 0.6
NPC_WEAPONS_SPREAD_MOVE_MULT_MED = 0.6
NPC_WEAPONS_SPREAD_MOVE_MULT_HIGH = 0.6
NPC_WEAPONS_SPREAD_MOVE_MULT_VHIGH = 0.6

NPC_WEAPONS_RELOAD_TIME_LOW = 1
NPC_WEAPONS_RELOAD_TIME_MED = 1.2
NPC_WEAPONS_RELOAD_TIME_HIGH = 2