local function AddPlayerModel( name, model )

	list.Set( "PlayerOptionsModel", name, model )
	player_manager.AddValidModel( name, model )
	
end



AddPlayerModel( "Bastila", 		"models/grealms/characters/bastila/bastila.mdl" )
AddPlayerModel( "Casual Jedi 01", 		"models/grealms/characters/casualjedi/casualjedi_01.mdl" )
AddPlayerModel( "Casual Jedi 0", 		"models/grealms/characters/casualjedi/casualjedi_02.mdl" )
AddPlayerModel( "Casual Jedi 03", 		"models/grealms/characters/casualjedi/casualjedi_03.mdl" )
AddPlayerModel( "Casual Jedi 04", 		"models/grealms/characters/casualjedi/casualjedi_04.mdl" )
AddPlayerModel( "Casual Jedi 05", 		"models/grealms/characters/casualjedi/casualjedi_05.mdl" )
AddPlayerModel( "Casual Jedi 06", 		"models/grealms/characters/casualjedi/casualjedi_06.mdl" )
AddPlayerModel( "Casual Jedi 07", 		"models/grealms/characters/casualjedi/casualjedi_07.mdl" )
AddPlayerModel( "Casual Jedi 08", 		"models/grealms/characters/casualjedi/casualjedi_08.mdl" )
AddPlayerModel( "Casual Jedi 09", 		"models/grealms/characters/casualjedi/casualjedi_09.mdl" )
AddPlayerModel( "Dark Jedi", 		"models/grealms/characters/darkjedi/darkjedi.mdl" )
AddPlayerModel( "Dark Nihilus", 		"models/grealms/characters/darthnihilus/darthnihilus.mdl" )
AddPlayerModel( "Jedi Robes 01", 		"models/grealms/characters/jedirobes/jedirobes_01.mdl" )
AddPlayerModel( "Jedi Robes 02", 		"models/grealms/characters/jedirobes/jedirobes_02.mdl" )
AddPlayerModel( "Jedi Robes 03", 		"models/grealms/characters/jedirobes/jedirobes_03.mdl" )
AddPlayerModel( "Jedi Robes 04", 		"models/grealms/characters/jedirobes/jedirobes_04.mdl" )
AddPlayerModel( "Jedi Robes 05", 		"models/grealms/characters/jedirobes/jedirobes_05.mdl" )
AddPlayerModel( "Jedi Robes 06", 		"models/grealms/characters/jedirobes/jedirobes_06.mdl" )
AddPlayerModel( "Jedi Robes 07", 		"models/grealms/characters/jedirobes/jedirobes_07.mdl" )
AddPlayerModel( "Jedi Robes 08", 		"models/grealms/characters/jedirobes/jedirobes_08.mdl" )
AddPlayerModel( "Jedi Robes 09", 		"models/grealms/characters/jedirobes/jedirobes_09.mdl" )
AddPlayerModel( "Malak", 		"models/grealms/characters/malak/malak.mdl" )
AddPlayerModel( "Padawan 01", 		"models/grealms/characters/padawan/padawan_01.mdl" )
AddPlayerModel( "Padawan 02", 		"models/grealms/characters/padawan/padawan_02.mdl" )
AddPlayerModel( "Padawan 03", 		"models/grealms/characters/padawan/padawan_03.mdl" )
AddPlayerModel( "Padawan 04", 		"models/grealms/characters/padawan/padawan_04.mdl" )
AddPlayerModel( "Padawan 05", 		"models/grealms/characters/padawan/padawan_05.mdl" )
AddPlayerModel( "Padawan 06", 		"models/grealms/characters/padawan/padawan_06.mdl" )
AddPlayerModel( "Padawan 07", 		"models/grealms/characters/padawan/padawan_07.mdl" )
AddPlayerModel( "Padawan 08", 		"models/grealms/characters/padawan/padawan_08.mdl" )
AddPlayerModel( "Padawan 09", 		"models/grealms/characters/padawan/padawan_09.mdl" )
AddPlayerModel( "Kotor Male 01", 		"models/player/x227man/mkotor_1.mdl" )
AddPlayerModel( "Kotor Male 02", 		"models/player/x227man/mkotor_2.mdl" )
AddPlayerModel( "Kotor Male 03", 		"models/player/x227man/mkotor_3.mdl" )
AddPlayerModel( "Kotor Male 04", 		"models/player/x227man/mkotor_4.mdl" )
AddPlayerModel( "Kotor Male 05", 		"models/player/x227man/mkotor_5.mdl" )
AddPlayerModel( "Kotor Male 06", 		"models/player/x227man/mkotor_6.mdl" )
AddPlayerModel( "Kotor Male 07", 		"models/player/x227man/mkotor_7.mdl" )
AddPlayerModel( "Kotor Male 08", 		"models/player/x227man/mkotor_8.mdl" )
AddPlayerModel( "Kotor Male 09", 		"models/player/x227man/mkotor_9.mdl" )